export enum Genre {
  Action = 'Action',
  RPG = 'RPG',
  Strategy = 'Strategy',
  Horror = 'Horror',
  GothicVictorian = 'Gothic / Victorian',
  SciFi = 'Sci-fi',
  Stealth = 'Stealth',
  Platformer = 'Platformer',
  Adventure = 'Adventure',
  Noir = 'Noir',
  SoulsLike = 'Souls-like',
  Shooter = 'Shooter',
  Puzzle = 'Puzzle',
  Simulation = 'Simulation',
  Metroidvania = 'Metroidvania',
}
