export enum Mood {
  ATMOSPHERIC = 'Atmospheric',
  CHALLENGING = 'Challenging',
  CHILL = 'Chill',
  COZY = 'Cozy',
  DARK_AND_TENSE = 'Dark & tense',
  EMOTIONAL = 'Emotional',
  EXCITED = 'Excited',
  EXPLORATORY = 'Exploratory',
  FANTASY = 'Fantasy',
  FOCUSED = 'Focused',
  INTENSE = 'Intense',
  MINDLESS_FUN = 'Mindless fun',
  RELAXED = 'Relaxed',
  SCI_FI = 'Sci-fi',
  STORY_HEAVY = 'Story-heavy',
}