export enum Theme {
  Action = 'Action',
  Fantasy = 'Fantasy',
  ScienceFiction = 'Science fiction',
  Horror = 'Horror',
  Thriller = 'Thriller',
  Survival = 'Survival',
  Historical = 'Historical',
  Stealth = 'Stealth',
  Comedy = 'Comedy',
  Business = 'Business',
  Drama = 'Drama',
  NonFiction = 'Non-fiction',
  Sandbox = 'Sandbox',
  Educational = 'Educational',
  Kids = 'Kids',
  OpenWorld = 'Open world',
  Warfare = 'Warfare',
  Party = 'Party',
  X4 = '4X (explore, expand, exploit, and exterminate)',
  Erotic = 'Erotic',
  Mystery = 'Mystery',
  Romance = 'Romance'
}
